name: preprocessing pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Run preprocessing script
        run: |
          python ./preprocessing/automate_HafizIkhsan.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add preprocessing/loan_approval_preprocessed.csv
          git commit -m "chore: auto-generate preprocessed data" || echo "No changes to commit"
          git push
